"""Seed the demo database.

Idempotent: it does nothing when users already exist, unless WATHIQ_FORCE_SEED=1.
Run with `python -m app.db.seed` (the container entrypoint does this on start).

All data is synthetic. See app/db/seed_data.py.
"""

from __future__ import annotations

import asyncio
import logging
import random
from datetime import UTC, datetime, timedelta
from typing import Any

from sqlalchemy import func, select, text
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.config import settings
from app.core.security import hash_password
from app.db import models
from app.db.enums import (
    ActorType,
    CaseStatus,
    CaseType,
    DocTypeKey,
    DocumentStatus,
    FieldStatus,
    FindingStatus,
    Language,
    Priority,
    PromptStatus,
    QualityBand,
    ReviewDecision,
    ReviewReason,
    ReviewStatus,
    RiskLevel,
    Role,
    Severity,
)
from app.db.seed_data import (
    COMPANIES,
    DOC_TYPE_DEFS,
    FINDING_TEMPLATES,
    LEGAL_FORMS,
    LICENSING_AUTHORITIES,
    PEOPLE,
    PROMPT_DEFS,
)
from app.db.session import SessionLocal
from app.services.catalog import DOC_TYPE_LABELS, REVIEW_REASON_LABELS
from app.services.demo_accounts import DEMO_ACCOUNTS
from app.services.pdf import simple_pdf
from app.services.storage import get_storage

logger = logging.getLogger("wathiq.seed")

rng = random.Random(20260919)

MODEL_VERSION = "fake-model-1" if settings.is_demo else "azure-foundry"
FOOTER = "SYNTHETIC DEMO DOCUMENT - generated by Wathiq. Not a real record."

# How the 30 demo cases are spread across statuses, so every screen has something to show.
STATUS_PLAN: list[tuple[CaseStatus, int]] = [
    (CaseStatus.completed, 11),
    (CaseStatus.needs_review, 6),
    (CaseStatus.in_review, 3),
    (CaseStatus.approved, 2),
    (CaseStatus.rejected, 2),
    (CaseStatus.processing, 2),
    (CaseStatus.posting, 1),
    (CaseStatus.failed, 1),
    (CaseStatus.intake, 2),
]


# --------------------------------------------------------------------------- helpers
def _date(days_from_now: int) -> str:
    return (datetime.now(UTC) + timedelta(days=days_from_now)).date().isoformat()


def _licence_number() -> str:
    return f"CN-{rng.randint(1000000, 9999999)}"


def _emirates_id() -> str:
    return f"784-{rng.randint(1960, 2005)}-{rng.randint(1000000, 9999999)}-{rng.randint(1, 9)}"


def _passport_number() -> str:
    return f"{rng.choice('ABCEKNPRZ')}{rng.randint(1000000, 9999999)}"


def _iban() -> str:
    return "AE" + "".join(str(rng.randint(0, 9)) for _ in range(21))


def _confidence(high: bool) -> float:
    return round(rng.uniform(0.93, 0.995) if high else rng.uniform(0.52, 0.86), 3)


def _calibrate(raw: float) -> float:
    """The model is slightly over-confident; calibration pulls high values down a little."""
    return round(max(0.05, min(0.99, raw - (raw - 0.5) * 0.08)), 3)


# --------------------------------------------------------------------------- users
async def seed_users(db: AsyncSession) -> dict[Role, models.User]:
    password_hash = hash_password(settings.demo_password)
    users: dict[Role, models.User] = {}
    for account in DEMO_ACCOUNTS:
        user = models.User(
            email=account.email,
            full_name=account.full_name,
            full_name_ar=account.full_name_ar,
            role=account.role,
            hashed_password=password_hash,
            is_active=True,
            is_demo=True,
        )
        db.add(user)
        users[account.role] = user
    await db.flush()
    logger.info("seeded %d demo users", len(users))
    return users


# --------------------------------------------------------------------------- config
async def seed_document_types(db: AsyncSession) -> dict[DocTypeKey, models.DocumentType]:
    out: dict[DocTypeKey, models.DocumentType] = {}
    for definition in DOC_TYPE_DEFS:
        rules = [
            {**rule, "severity": Severity(rule["severity"]).value}
            for rule in definition["rules"]  # type: ignore[union-attr]
        ]
        doc_type = models.DocumentType(
            key=definition["key"],
            name_en=definition["name_en"],
            name_ar=definition["name_ar"],
            description=definition["description"],
            version=definition["version"],
            prompt_key=definition["prompt_key"],
            rules_version=definition["rules_version"],
            field_schema=definition["fields"],
            rules=rules,
            is_active=True,
        )
        db.add(doc_type)
        out[definition["key"]] = doc_type  # type: ignore[index]
    await db.flush()
    logger.info("seeded %d document types", len(out))
    return out


async def seed_prompts(db: AsyncSession) -> None:
    for definition in PROMPT_DEFS:
        prompt = models.Prompt(
            key=definition["key"],
            name=definition["name"],
            description=definition["description"],
            document_type=definition["document_type"],
        )
        db.add(prompt)
        await db.flush()
        for index, version in enumerate(definition["versions"]):  # type: ignore[union-attr]
            created = datetime.now(UTC) - timedelta(days=40 - index * 12)
            approved = version.get("approved_by")
            db.add(
                models.PromptVersion(
                    prompt_id=prompt.id,
                    version=version["version"],
                    status=PromptStatus(version["status"]),
                    body=version["body"],
                    notes=version["notes"],
                    eval_score=None,
                    created_by=version.get("created_by", ""),
                    created_at=created,
                    approved_by=approved,
                    approved_at=created + timedelta(hours=6) if approved else None,
                )
            )
    await db.flush()
    logger.info("seeded %d prompts", len(PROMPT_DEFS))


# --------------------------------------------------------------------------- cases
def _document_values(doc_type: DocTypeKey, company: dict[str, str], person: dict[str, str]):
    """Return (field values, pdf lines) for one document."""
    if doc_type == DocTypeKey.trade_license:
        expiry = _date(rng.choice([-30, 60, 120, 240, 400]))
        values = {
            "license_number": _licence_number(),
            "company_name_en": company["en"],
            "company_name_ar": company["ar"],
            "legal_form": rng.choice(LEGAL_FORMS),
            "licensing_authority": rng.choice(LICENSING_AUTHORITIES),
            "business_activity": company["activity"],
            "issue_date": _date(-rng.randint(400, 1200)),
            "expiry_date": expiry,
            "registered_address": f"Office {rng.randint(100, 2400)}, Business Tower (synthetic)",
        }
    elif doc_type == DocTypeKey.emirates_id:
        values = {
            "id_number": _emirates_id(),
            "full_name_en": person["en"],
            "full_name_ar": person["ar"],
            "nationality": person["nationality"],
            "date_of_birth": _date(-rng.randint(8000, 18000)),
            "expiry_date": _date(rng.choice([-15, 90, 300, 700])),
            "card_number": str(rng.randint(100000000, 999999999)),
        }
    elif doc_type == DocTypeKey.passport:
        values = {
            "passport_number": _passport_number(),
            "full_name": person["en"],
            "nationality": person["nationality"],
            "date_of_birth": _date(-rng.randint(8000, 18000)),
            "issue_date": _date(-rng.randint(400, 2500)),
            "expiry_date": _date(rng.choice([100, 400, 900, 1600])),
        }
    elif doc_type == DocTypeKey.moa:
        values = {
            "company_name_en": company["en"],
            "share_capital": f"AED {rng.choice([150, 300, 500, 1000, 2500]) * 1000:,}",
            "shareholders": f"{person['en']} (60%), {rng.choice(PEOPLE)['en']} (40%)",
            "incorporation_date": _date(-rng.randint(600, 3000)),
            "notary_reference": f"NOT-{rng.randint(10000, 99999)}",
        }
    else:  # salary certificate
        basic = rng.choice([12000, 18000, 22000, 30000, 45000])
        values = {
            "employee_name": person["en"],
            "employer_name": company["en"],
            "designation": rng.choice(
                ["Operations Manager", "Senior Engineer", "Finance Lead", "Account Manager"]
            ),
            "basic_salary": f"AED {basic:,}",
            "total_salary": f"AED {int(basic * rng.uniform(1.2, 1.6)):,}",
            "issue_date": _date(-rng.randint(5, 120)),
            "iban": _iban(),
        }
    lines = [(key.replace("_", " "), str(value)) for key, value in values.items()]
    return values, lines


async def seed_cases(
    db: AsyncSession,
    users: dict[Role, models.User],
    doc_types: dict[DocTypeKey, models.DocumentType],
) -> None:
    storage = get_storage()
    ops = users[Role.ops_officer]
    reviewer = users[Role.reviewer]
    supervisor = users[Role.supervisor]

    schema_by_key = {
        definition["key"]: {f["name"]: f for f in definition["fields"]}  # type: ignore[index]
        for definition in DOC_TYPE_DEFS
    }

    statuses: list[CaseStatus] = []
    for status, count in STATUS_PLAN:
        statuses.extend([status] * count)

    year = datetime.now(UTC).year
    for index, status in enumerate(statuses, start=1):
        company = COMPANIES[index % len(COMPANIES)]
        person = PEOPLE[index % len(PEOPLE)]
        # Half a day for the newest cases, up to 14 days for the oldest.
        age_hours = int(rng.triangular(1, 14 * 24, 40)) if index > 3 else rng.randint(1, 8)
        created_at = datetime.now(UTC) - timedelta(hours=age_hours)

        is_salary = index % 10 == 0
        case_type = CaseType.salary_certificate if is_salary else CaseType.kyc_refresh
        needs_human = status in (
            CaseStatus.needs_review,
            CaseStatus.in_review,
            CaseStatus.rejected,
        )
        reviewed_and_done = status in (CaseStatus.completed, CaseStatus.approved) and index % 3 == 0
        straight_through = status in (CaseStatus.completed, CaseStatus.approved) and not (
            reviewed_and_done
        )
        confident = not (needs_human or reviewed_and_done)

        case = models.Case(
            reference=f"WTQ-{year}-{index:04d}",
            case_type=case_type,
            customer_name=company["en"],
            customer_name_ar=company["ar"],
            status=status,
            risk_level=(
                RiskLevel.high
                if status in (CaseStatus.rejected, CaseStatus.failed)
                else RiskLevel.medium
                if needs_human
                else RiskLevel.low
            ),
            priority=rng.choice([Priority.normal, Priority.normal, Priority.high, Priority.urgent]),
            notes="",
            thread_id=f"wf_{rng.getrandbits(48):012x}",
            confidence=None
            if status in (CaseStatus.intake, CaseStatus.processing)
            else round(rng.uniform(0.93, 0.99) if confident else rng.uniform(0.61, 0.88), 3),
            straight_through=straight_through,
            processing_ms=None
            if status in (CaseStatus.intake, CaseStatus.processing)
            else rng.randint(18000, 95000),
            cost_usd=None
            if status in (CaseStatus.intake, CaseStatus.processing)
            else round(rng.uniform(0.011, 0.074), 4),
            created_by_id=ops.id,
            assigned_to_id=(
                reviewer.id
                if status == CaseStatus.in_review
                else supervisor.id
                if status == CaseStatus.failed
                else None
            ),
            sla_due_at=created_at + timedelta(hours=settings.review_sla_hours),
            completed_at=(
                created_at + timedelta(minutes=rng.randint(12, 240))
                if status in (CaseStatus.completed, CaseStatus.rejected)
                else None
            ),
            created_at=created_at,
            updated_at=created_at + timedelta(minutes=rng.randint(5, 300)),
        )
        db.add(case)
        await db.flush()

        # --- documents + fields
        doc_keys = (
            [DocTypeKey.salary_certificate]
            if is_salary
            else [DocTypeKey.trade_license, DocTypeKey.emirates_id, DocTypeKey.passport]
            + ([DocTypeKey.moa] if index % 2 == 0 else [])
        )
        order = 0
        for doc_key in doc_keys:
            values, lines = _document_values(doc_key, company, person)
            label = DOC_TYPE_LABELS[doc_key]
            pdf = simple_pdf(f"{label} (synthetic)", lines, FOOTER)
            filename = f"{doc_key.value}_{case.reference}.pdf"
            path = storage.save(case.id, filename, pdf)

            document = models.Document(
                case_id=case.id,
                filename=filename,
                doc_type=doc_key,
                language=Language.mixed if doc_key == DocTypeKey.trade_license else Language.en,
                mime_type="application/pdf",
                size_bytes=len(pdf),
                page_count=1,
                storage_path=path,
                ocr_confidence=round(rng.uniform(0.88, 0.995), 3),
                classification_confidence=round(rng.uniform(0.9, 0.999), 3),
                status=(
                    DocumentStatus.uploaded
                    if status == CaseStatus.intake
                    else DocumentStatus.extracted
                ),
                created_at=created_at + timedelta(seconds=rng.randint(5, 60)),
            )
            db.add(document)
            await db.flush()

            if status == CaseStatus.intake:
                continue

            schema = schema_by_key[doc_key]
            for field_name, value in values.items():
                meta: dict[str, Any] = schema.get(field_name, {})
                critical = bool(meta.get("is_critical"))
                # A doubtful case has one weak critical field — that is what triggers review.
                high = confident or not critical or rng.random() > 0.6
                raw = _confidence(high)
                # A reviewer looked at this case and sometimes changed a value. Those
                # corrections are the ground truth the confidence curve is fitted on
                # (services/assurance.py), so the demo needs some — and they have to be
                # realistic: a low score is corrected far more often than a high one.
                corrected = reviewed_and_done and rng.random() < (0.45 if raw < 0.85 else 0.04)
                db.add(
                    models.ExtractedField(
                        case_id=case.id,
                        document_id=document.id,
                        name=field_name,
                        label_en=meta.get("label_en", field_name.replace("_", " ").title()),
                        label_ar=meta.get("label_ar", ""),
                        value=str(value),
                        corrected_value=f"{value} (corrected)" if corrected else None,
                        confidence=raw,
                        calibrated_confidence=_calibrate(raw),
                        status=(
                            FieldStatus.corrected
                            if corrected
                            else FieldStatus.auto_accepted
                            if raw >= 0.9
                            else FieldStatus.needs_review
                        ),
                        is_critical=critical,
                        page=1,
                        bbox=[
                            round(rng.uniform(0.08, 0.15), 3),
                            round(0.12 + order * 0.055, 3),
                            round(rng.uniform(0.35, 0.6), 3),
                            0.035,
                        ],
                        source_text=f"{field_name.replace('_', ' ')}: {value}",
                        order_index=order,
                        created_at=document.created_at,
                    )
                )
                order += 1

        # --- findings
        findings_for_case: list[dict[str, Any]] = []
        if needs_human or status == CaseStatus.failed:
            findings_for_case.append(FINDING_TEMPLATES[index % len(FINDING_TEMPLATES)])
        if reviewed_and_done or index % 7 == 0:
            findings_for_case.append(FINDING_TEMPLATES[(index + 3) % len(FINDING_TEMPLATES)])

        resolved = status in (CaseStatus.completed, CaseStatus.approved)
        for template in findings_for_case:
            db.add(
                models.Finding(
                    case_id=case.id,
                    code=template["code"],
                    severity=template["severity"],
                    title=template["title"],
                    description=template["description"],
                    policy_citation=template["policy_citation"],
                    policy_quote=template["policy_quote"],
                    status=FindingStatus.resolved if resolved else FindingStatus.open,
                    created_at=created_at + timedelta(minutes=2),
                )
            )

        # --- review task
        if needs_human or reviewed_and_done:
            default_reason = "LOW_CONFIDENCE_CRITICAL_FIELD"
            reason_code = findings_for_case[0]["code"] if findings_for_case else default_reason
            mandatory = reason_code in (
                "SANCTIONS_POSSIBLE_MATCH",
                "DOCUMENT_EXPIRED",
                "SUSPECTED_INJECTION",
            )
            task_status = (
                ReviewStatus.pending
                if status == CaseStatus.needs_review
                else ReviewStatus.in_progress
                if status == CaseStatus.in_review
                else ReviewStatus.completed
            )
            decision = None
            if task_status == ReviewStatus.completed:
                decision = (
                    ReviewDecision.reject
                    if status == CaseStatus.rejected
                    else rng.choice([ReviewDecision.approve, ReviewDecision.correct])
                )
            db.add(
                models.ReviewTask(
                    case_id=case.id,
                    reason=ReviewReason.mandatory if mandatory else ReviewReason.dynamic,
                    reason_code=reason_code,
                    reason_label=REVIEW_REASON_LABELS.get(reason_code, "Needs human review"),
                    status=task_status,
                    assigned_role=Role.reviewer,
                    assigned_to_id=(
                        reviewer.id if task_status != ReviewStatus.pending else None
                    ),
                    sla_due_at=created_at + timedelta(hours=settings.review_sla_hours),
                    decision=decision,
                    decision_reason_code=(
                        "VALUES_CONFIRMED"
                        if decision == ReviewDecision.approve
                        else "OCR_ERROR"
                        if decision == ReviewDecision.correct
                        else "ILLEGIBLE_DOCUMENT"
                        if decision
                        else None
                    ),
                    decision_note=None,
                    completed_at=(
                        created_at + timedelta(minutes=rng.randint(20, 180)) if decision else None
                    ),
                    created_at=created_at + timedelta(minutes=3),
                )
            )

        # --- timeline / audit events
        await _seed_events(
            db,
            case=case,
            status=status,
            documents=len(doc_keys),
            ops=ops,
            reviewer=reviewer,
            findings=findings_for_case,
            created_at=created_at,
        )

    await db.flush()
    logger.info("seeded %d cases", len(statuses))


async def _seed_events(
    db: AsyncSession,
    *,
    case: models.Case,
    status: CaseStatus,
    documents: int,
    ops: models.User,
    reviewer: models.User,
    findings: list[dict[str, Any]],
    created_at: datetime,
) -> None:
    steps: list[tuple[int, str, str, str, ActorType, str | None, int | None]] = [
        (0, "case.created", f"Case {case.reference} created for {case.customer_name}",
         ops.full_name, ActorType.user, None, None),
        (20, "documents.uploaded", f"{documents} document(s) uploaded",
         ops.full_name, ActorType.user, None, None),
    ]
    if status != CaseStatus.intake:
        steps += [
            (45, "pipeline.started", "Conductor workflow started", "conductor",
             ActorType.system, None, None),
            (50, "guardrails.checked",
             "Prompt shield and PII tokenisation passed", "guardrails",
             ActorType.system, None, 220),
            (60, "documents.classified",
             f"{documents} document(s) classified", "supervisor_node",
             ActorType.agent, "classify_document@1.1.0", 1400),
            (95, "fields.extracted",
             "Fields extracted with per-field confidence", "worker_extract",
             ActorType.agent, "extract_trade_license@2.1.0", 5200),
            (140, "critic.reviewed", "Critic challenged the doubtful fields", "critic_node",
             ActorType.agent, "critic_challenge@1.0.0", 2100),
            (170, "rules.validated", "Cross-field rules applied (rules v1.1.0)", "validator_node",
             ActorType.agent, None, 180),
            (180, "confidence.calibrated", "Confidence calibrated on the golden set",
             "calibrator", ActorType.system, None, 40),
        ]
    for template in findings:
        steps.append(
            (200, "finding.raised", f"Finding raised: {template['title']}", "validator_node",
             ActorType.agent, None, None)
        )

    if status in (CaseStatus.needs_review, CaseStatus.in_review):
        steps.append(
            (210, "review.required", "Review gate paused the graph for a human",
             "review_gate", ActorType.agent, None, None)
        )
    if status == CaseStatus.in_review:
        steps.append(
            (900, "review.claimed", f"{reviewer.full_name} claimed the review",
             reviewer.full_name, ActorType.user, None, None)
        )
    if status in (CaseStatus.completed, CaseStatus.approved, CaseStatus.posting):
        if case.straight_through:
            steps.append(
                (215, "review.skipped", "Confidence above threshold — no human review needed",
                 "review_gate", ActorType.agent, None, None)
            )
        else:
            steps += [
                (900, "review.claimed", f"{reviewer.full_name} claimed the review",
                 reviewer.full_name, ActorType.user, None, None),
                (1500, "review.approve", f"{reviewer.full_name} approved the extraction",
                 reviewer.full_name, ActorType.user, None, None),
            ]
    if status in (CaseStatus.completed, CaseStatus.posting):
        steps.append(
            (1600, "corebanking.posted",
             "Posted to the core banking system (SIMULATED), idempotency key reused safely",
             "core_banking_mcp", ActorType.system, None, 320)
        )
    if status == CaseStatus.completed:
        steps.append(
            (1650, "case.completed", f"{case.reference} completed", "conductor",
             ActorType.system, None, None)
        )
    if status == CaseStatus.rejected:
        steps.append(
            (1500, "review.reject", f"{reviewer.full_name} rejected the documents",
             reviewer.full_name, ActorType.user, None, None)
        )
    if status == CaseStatus.failed:
        steps.append(
            (300, "pipeline.failed",
             "Extraction failed: document unreadable after 2 retries", "worker_extract",
             ActorType.agent, "extract_trade_license@2.1.0", 8800)
        )

    for offset, action, label, actor, actor_type, prompt_version, duration in steps:
        db.add(
            models.Event(
                case_id=case.id,
                actor=actor,
                actor_type=actor_type,
                action=action,
                label=label,
                detail={"thread_id": case.thread_id},
                prompt_version=prompt_version,
                model_version=MODEL_VERSION if actor_type == ActorType.agent else None,
                duration_ms=duration,
                created_at=created_at + timedelta(seconds=offset),
            )
        )


# --------------------------------------------------------------------------- quality lab
BAND_PLAN: dict[QualityBand, tuple[int, int]] = {
    QualityBand.model: (42, 2),
    QualityBand.prompt: (68, 3),
    QualityBand.agent: (35, 1),
    QualityBand.ai_security: (24, 0),
    QualityBand.adversarial: (31, 4),
}

BAND_CASE_NAMES: dict[QualityBand, list[str]] = {
    QualityBand.model: [
        "Reads a clean English trade licence",
        "Reads an Arabic trade licence",
        "Handles a rotated scan",
        "Refuses to guess a missing field",
    ],
    QualityBand.prompt: [
        "Golden set: licence number exact match",
        "Golden set: expiry date normalised",
        "Sensitivity: reordered instructions give the same answer",
        "Sensitivity: synonym swap gives the same answer",
    ],
    QualityBand.agent: [
        "Routes a low-confidence critical field to review",
        "Stops after 2 self-correction attempts",
        "Calls the registry tool only when names disagree",
        "Resumes from the checkpoint after a reviewer decision",
    ],
    QualityBand.ai_security: [
        "Ignores an instruction hidden in the document",
        "Tokenises the Emirates ID before logging",
        "Strips HTML and zero-width characters from output",
        "Blocks unsafe content before the model call",
    ],
    QualityBand.adversarial: [
        "Altered expiry date is flagged, not accepted",
        "Blurred scan lowers confidence instead of guessing",
        "Arabic/English name mismatch raises a finding",
        "Hidden white-on-white instruction is ignored",
    ],
}


async def seed_quality(db: AsyncSession) -> None:
    now = datetime.now(UTC)
    for band, (total, failed) in BAND_PLAN.items():
        for run_index in range(3):
            started = now - timedelta(days=run_index * 3, hours=rng.randint(1, 9))
            run_failed = failed if run_index == 0 else failed + rng.randint(0, 3)
            run_passed = total - run_failed
            run = models.QualityRun(
                band=band,
                started_at=started,
                finished_at=started + timedelta(minutes=rng.randint(2, 11)),
                passed=run_passed,
                failed=run_failed,
                score=round(run_passed / total, 4),
                triggered_by="ci" if run_index else "Rashid Belhoul",
                commit_sha=f"{rng.getrandbits(28):07x}",
                created_at=started,
            )
            db.add(run)
            await db.flush()

            if run_index == 0:
                names = BAND_CASE_NAMES[band]
                for case_index, name in enumerate(names):
                    passed = case_index >= run_failed
                    db.add(
                        models.QualityCase(
                            run_id=run.id,
                            name=name,
                            band=band,
                            passed=passed,
                            expected="exact match with the answer key",
                            actual="match" if passed else "value differs from the answer key",
                            note=""
                            if passed
                            else "Added to the regression set from a reviewer correction.",
                            is_regression=not passed,
                        )
                    )
    await db.flush()
    logger.info("seeded quality runs for %d bands", len(BAND_PLAN))


async def seed_calibration(db: AsyncSession) -> None:
    """A slightly over-confident model: stated confidence sits above observed accuracy."""
    for step in range(10):
        predicted = round(0.05 + step * 0.1, 2)
        observed = round(min(0.99, max(0.02, predicted - 0.06 + rng.uniform(-0.03, 0.03))), 3)
        db.add(
            models.CalibrationPoint(
                predicted=predicted,
                observed=observed,
                n=rng.randint(40, 220),
                model_version=MODEL_VERSION,
            )
        )
    await db.flush()


# --------------------------------------------------------------------------- entry point
async def already_seeded(db: AsyncSession) -> bool:
    count = (await db.execute(select(func.count(models.User.id)))).scalar_one()
    return count > 0


# TRUNCATE, not DELETE. Since M4 the `events` table carries a trigger that rejects every
# UPDATE and DELETE, because an audit trail that the application can edit is not an audit trail.
# TRUNCATE does not fire row triggers, and that is the right boundary rather than a loophole:
# it needs table-owner rights and empties the table completely, so it cannot be used to quietly
# alter one record — which is the thing the control exists to prevent. Wiping a demo database is
# a visible, wholesale act; rewriting history is not.
_CLEAR_TABLES = (
    "regression_examples",
    "calibration_experiments",
    "quality_cases",
    "quality_runs",
    "calibration_points",
    "calibration_curves",
    "postings",
    "events",
    "review_tasks",
    "findings",
    "extracted_fields",
    "documents",
    "cases",
    "prompt_versions",
    "prompts",
    "document_types",
    "users",
)


async def clear_all(db: AsyncSession) -> None:
    await db.execute(
        text(f"TRUNCATE TABLE {', '.join(_CLEAR_TABLES)} RESTART IDENTITY CASCADE")
    )
    await db.flush()


async def seed(force: bool = False) -> None:
    async with SessionLocal() as db:
        if await already_seeded(db):
            if not force:
                logger.info("database already seeded — nothing to do")
                return
            logger.warning("force seed: clearing existing data")
            await clear_all(db)

        users = await seed_users(db)
        doc_types = await seed_document_types(db)
        await seed_prompts(db)
        await seed_cases(db, users, doc_types)
        await seed_quality(db)
        await seed_calibration(db)
        await db.commit()
        logger.info("seed complete")


def main() -> None:
    logging.basicConfig(level="INFO", format="%(levelname)s %(name)s | %(message)s")
    import os

    asyncio.run(seed(force=os.environ.get("WATHIQ_FORCE_SEED") == "1"))


if __name__ == "__main__":
    main()
