"""initial schema

Revision ID: 87c6c95ba42a
Revises: 
Create Date: 2026-09-19 22:31:34.355527
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '87c6c95ba42a'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Hand-added: autogenerate does not emit these.
    # pgvector is needed from M3 (policy RAG); creating it now keeps one migration path.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # Global ordering for the append-only event log.
    op.execute("CREATE SEQUENCE IF NOT EXISTS events_seq")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calibration_points',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('predicted', sa.Float(), nullable=False),
    sa.Column('observed', sa.Float(), nullable=False),
    sa.Column('n', sa.Integer(), nullable=False),
    sa.Column('model_version', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('observed >= 0 AND observed <= 1', name=op.f('ck_calibration_points_observed_range')),
    sa.CheckConstraint('predicted >= 0 AND predicted <= 1', name=op.f('ck_calibration_points_predicted_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_calibration_points'))
    )
    op.create_index(op.f('ix_calibration_points_created_at'), 'calibration_points', ['created_at'], unique=False)
    op.create_table('document_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.Enum('trade_license', 'emirates_id', 'passport', 'moa', 'salary_certificate', 'unknown', name='doc_type_key', native_enum=False, length=32), nullable=False),
    sa.Column('name_en', sa.String(length=120), nullable=False),
    sa.Column('name_ar', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('prompt_key', sa.String(length=80), nullable=False),
    sa.Column('rules_version', sa.String(length=20), nullable=False),
    sa.Column('field_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rules', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_types'))
    )
    op.create_index(op.f('ix_document_types_created_at'), 'document_types', ['created_at'], unique=False)
    op.create_index(op.f('ix_document_types_key'), 'document_types', ['key'], unique=True)
    op.create_table('prompts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('document_type', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prompts'))
    )
    op.create_index(op.f('ix_prompts_created_at'), 'prompts', ['created_at'], unique=False)
    op.create_index(op.f('ix_prompts_key'), 'prompts', ['key'], unique=True)
    op.create_table('quality_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('band', sa.Enum('model', 'prompt', 'agent', 'ai_security', 'adversarial', name='quality_band', native_enum=False, length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('passed', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('triggered_by', sa.String(length=120), nullable=False),
    sa.Column('commit_sha', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quality_runs'))
    )
    op.create_index(op.f('ix_quality_runs_band'), 'quality_runs', ['band'], unique=False)
    op.create_index(op.f('ix_quality_runs_created_at'), 'quality_runs', ['created_at'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('full_name_ar', sa.String(length=160), nullable=False),
    sa.Column('role', sa.Enum('ops_officer', 'reviewer', 'supervisor', 'admin', 'auditor', name='role', native_enum=False, length=32), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('cases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reference', sa.String(length=32), nullable=False),
    sa.Column('case_type', sa.Enum('kyc_refresh', 'salary_certificate', name='case_type', native_enum=False, length=32), nullable=False),
    sa.Column('customer_name', sa.String(length=200), nullable=False),
    sa.Column('customer_name_ar', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('intake', 'processing', 'needs_review', 'in_review', 'approved', 'posting', 'completed', 'rejected', 'failed', name='case_status', native_enum=False, length=32), nullable=False),
    sa.Column('risk_level', sa.Enum('low', 'medium', 'high', name='risk_level', native_enum=False, length=32), nullable=False),
    sa.Column('priority', sa.Enum('normal', 'high', 'urgent', name='priority', native_enum=False, length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('thread_id', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('straight_through', sa.Boolean(), nullable=False),
    sa.Column('processing_ms', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('assigned_to_id', sa.UUID(), nullable=True),
    sa.Column('sla_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], name=op.f('fk_cases_assigned_to_id_users')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_cases_created_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cases'))
    )
    op.create_index(op.f('ix_cases_assigned_to_id'), 'cases', ['assigned_to_id'], unique=False)
    op.create_index(op.f('ix_cases_created_at'), 'cases', ['created_at'], unique=False)
    op.create_index(op.f('ix_cases_customer_name'), 'cases', ['customer_name'], unique=False)
    op.create_index(op.f('ix_cases_reference'), 'cases', ['reference'], unique=True)
    op.create_index(op.f('ix_cases_status'), 'cases', ['status'], unique=False)
    op.create_index('ix_cases_status_created', 'cases', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_cases_thread_id'), 'cases', ['thread_id'], unique=False)
    op.create_table('prompt_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('prompt_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('draft', 'approved', 'retired', name='prompt_status', native_enum=False, length=32), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('eval_score', sa.Float(), nullable=True),
    sa.Column('created_by', sa.String(length=160), nullable=False),
    sa.Column('approved_by', sa.String(length=160), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompts.id'], name=op.f('fk_prompt_versions_prompt_id_prompts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prompt_versions')),
    sa.UniqueConstraint('prompt_id', 'version', name='uq_prompt_version')
    )
    op.create_index(op.f('ix_prompt_versions_created_at'), 'prompt_versions', ['created_at'], unique=False)
    op.create_index(op.f('ix_prompt_versions_prompt_id'), 'prompt_versions', ['prompt_id'], unique=False)
    op.create_table('quality_cases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('band', sa.Enum('model', 'prompt', 'agent', 'ai_security', 'adversarial', name='case_quality_band', native_enum=False, length=32), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('expected', sa.Text(), nullable=False),
    sa.Column('actual', sa.Text(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('is_regression', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['quality_runs.id'], name=op.f('fk_quality_cases_run_id_quality_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quality_cases'))
    )
    op.create_index(op.f('ix_quality_cases_run_id'), 'quality_cases', ['run_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('doc_type', sa.Enum('trade_license', 'emirates_id', 'passport', 'moa', 'salary_certificate', 'unknown', name='document_doc_type', native_enum=False, length=32), nullable=False),
    sa.Column('language', sa.Enum('en', 'ar', 'mixed', name='language', native_enum=False, length=32), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.String(length=512), nullable=False),
    sa.Column('ocr_confidence', sa.Float(), nullable=True),
    sa.Column('classification_confidence', sa.Float(), nullable=True),
    sa.Column('ocr_text', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('uploaded', 'ocr', 'classified', 'extracted', 'failed', name='document_status', native_enum=False, length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_documents_case_id_cases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents'))
    )
    op.create_index(op.f('ix_documents_case_id'), 'documents', ['case_id'], unique=False)
    op.create_index(op.f('ix_documents_created_at'), 'documents', ['created_at'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('seq', sa.BigInteger(), server_default=sa.text("nextval('events_seq')"), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=True),
    sa.Column('actor', sa.String(length=160), nullable=False),
    sa.Column('actor_type', sa.Enum('user', 'agent', 'system', name='actor_type', native_enum=False, length=32), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('label', sa.String(length=300), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('prompt_version', sa.String(length=80), nullable=True),
    sa.Column('model_version', sa.String(length=80), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_events_case_id_cases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events'))
    )
    op.create_index(op.f('ix_events_action'), 'events', ['action'], unique=False)
    op.create_index(op.f('ix_events_case_id'), 'events', ['case_id'], unique=False)
    op.create_index('ix_events_case_seq', 'events', ['case_id', 'seq'], unique=False)
    op.create_index(op.f('ix_events_created_at'), 'events', ['created_at'], unique=False)
    op.create_index(op.f('ix_events_seq'), 'events', ['seq'], unique=True)
    op.create_table('findings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('severity', sa.Enum('info', 'warning', 'critical', name='severity', native_enum=False, length=32), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('policy_citation', sa.String(length=120), nullable=True),
    sa.Column('policy_quote', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('open', 'resolved', 'waived', name='finding_status', native_enum=False, length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_findings_case_id_cases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_findings'))
    )
    op.create_index(op.f('ix_findings_case_id'), 'findings', ['case_id'], unique=False)
    op.create_index(op.f('ix_findings_code'), 'findings', ['code'], unique=False)
    op.create_index(op.f('ix_findings_created_at'), 'findings', ['created_at'], unique=False)
    op.create_table('review_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.Enum('mandatory', 'dynamic', name='review_reason', native_enum=False, length=32), nullable=False),
    sa.Column('reason_code', sa.String(length=80), nullable=False),
    sa.Column('reason_label', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'completed', name='review_status', native_enum=False, length=32), nullable=False),
    sa.Column('assigned_role', sa.Enum('ops_officer', 'reviewer', 'supervisor', 'admin', 'auditor', name='review_assigned_role', native_enum=False, length=32), nullable=False),
    sa.Column('assigned_to_id', sa.UUID(), nullable=True),
    sa.Column('sla_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision', sa.Enum('approve', 'correct', 'reject', 'escalate', name='review_decision', native_enum=False, length=32), nullable=True),
    sa.Column('decision_reason_code', sa.String(length=80), nullable=True),
    sa.Column('decision_note', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], name=op.f('fk_review_tasks_assigned_to_id_users')),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_review_tasks_case_id_cases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_tasks'))
    )
    op.create_index(op.f('ix_review_tasks_assigned_to_id'), 'review_tasks', ['assigned_to_id'], unique=False)
    op.create_index(op.f('ix_review_tasks_case_id'), 'review_tasks', ['case_id'], unique=False)
    op.create_index(op.f('ix_review_tasks_created_at'), 'review_tasks', ['created_at'], unique=False)
    op.create_index(op.f('ix_review_tasks_status'), 'review_tasks', ['status'], unique=False)
    op.create_table('extracted_fields',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('label_en', sa.String(length=120), nullable=False),
    sa.Column('label_ar', sa.String(length=120), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('corrected_value', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('calibrated_confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('auto_accepted', 'needs_review', 'corrected', 'rejected', name='field_status', native_enum=False, length=32), nullable=False),
    sa.Column('is_critical', sa.Boolean(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('bbox', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_text', sa.Text(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_extracted_fields_case_id_cases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_extracted_fields_document_id_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_extracted_fields'))
    )
    op.create_index(op.f('ix_extracted_fields_case_id'), 'extracted_fields', ['case_id'], unique=False)
    op.create_index(op.f('ix_extracted_fields_created_at'), 'extracted_fields', ['created_at'], unique=False)
    op.create_index(op.f('ix_extracted_fields_document_id'), 'extracted_fields', ['document_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_extracted_fields_document_id'), table_name='extracted_fields')
    op.drop_index(op.f('ix_extracted_fields_created_at'), table_name='extracted_fields')
    op.drop_index(op.f('ix_extracted_fields_case_id'), table_name='extracted_fields')
    op.drop_table('extracted_fields')
    op.drop_index(op.f('ix_review_tasks_status'), table_name='review_tasks')
    op.drop_index(op.f('ix_review_tasks_created_at'), table_name='review_tasks')
    op.drop_index(op.f('ix_review_tasks_case_id'), table_name='review_tasks')
    op.drop_index(op.f('ix_review_tasks_assigned_to_id'), table_name='review_tasks')
    op.drop_table('review_tasks')
    op.drop_index(op.f('ix_findings_created_at'), table_name='findings')
    op.drop_index(op.f('ix_findings_code'), table_name='findings')
    op.drop_index(op.f('ix_findings_case_id'), table_name='findings')
    op.drop_table('findings')
    op.drop_index(op.f('ix_events_seq'), table_name='events')
    op.drop_index(op.f('ix_events_created_at'), table_name='events')
    op.drop_index('ix_events_case_seq', table_name='events')
    op.drop_index(op.f('ix_events_case_id'), table_name='events')
    op.drop_index(op.f('ix_events_action'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_documents_created_at'), table_name='documents')
    op.drop_index(op.f('ix_documents_case_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_quality_cases_run_id'), table_name='quality_cases')
    op.drop_table('quality_cases')
    op.drop_index(op.f('ix_prompt_versions_prompt_id'), table_name='prompt_versions')
    op.drop_index(op.f('ix_prompt_versions_created_at'), table_name='prompt_versions')
    op.drop_table('prompt_versions')
    op.drop_index(op.f('ix_cases_thread_id'), table_name='cases')
    op.drop_index('ix_cases_status_created', table_name='cases')
    op.drop_index(op.f('ix_cases_status'), table_name='cases')
    op.drop_index(op.f('ix_cases_reference'), table_name='cases')
    op.drop_index(op.f('ix_cases_customer_name'), table_name='cases')
    op.drop_index(op.f('ix_cases_created_at'), table_name='cases')
    op.drop_index(op.f('ix_cases_assigned_to_id'), table_name='cases')
    op.drop_table('cases')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_quality_runs_created_at'), table_name='quality_runs')
    op.drop_index(op.f('ix_quality_runs_band'), table_name='quality_runs')
    op.drop_table('quality_runs')
    op.drop_index(op.f('ix_prompts_key'), table_name='prompts')
    op.drop_index(op.f('ix_prompts_created_at'), table_name='prompts')
    op.drop_table('prompts')
    op.drop_index(op.f('ix_document_types_key'), table_name='document_types')
    op.drop_index(op.f('ix_document_types_created_at'), table_name='document_types')
    op.drop_table('document_types')
    op.drop_index(op.f('ix_calibration_points_created_at'), table_name='calibration_points')
    op.drop_table('calibration_points')
    # ### end Alembic commands ###
    op.execute("DROP SEQUENCE IF EXISTS events_seq")
